--- 

- hosts: home
  sudo: yes

  vars:
    php_packages:
      - php-apc
      - php-pear
      - php5-cli
      - php5-common
      - php5-curl
      - php5-fpm
      - php5-gd
      - php5-imagick
      - php5-mcrypt
      - php5-memcache
      - php5-memcached
      - php5-mysql
      - php5-sqlite
      - imagemagick-common

  name: Apply configuration

  roles:
    #- common
    #- user
    #- homeserver
    #- boogeyman
    #- repository
    - media-center